# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  evm1-1:
    image: ghcr.io/sygmaprotocol/sygma-solidity:evm1-v1.1.1
    container_name: evm1-1
    command: ganache-cli --chainId 1337 -d --db data/ --blockTime 2 > /dev/null
    # logging:
    #   driver: none
    ports:
      - "8545:8545"

  # SECOND CHAIN
  evm2-1:
    image: ghcr.io/sygmaprotocol/sygma-solidity:evm2-v1.1.1
    command: ganache-cli --chainId 1338 -d --db data/ --blockTime 2 > /dev/null
    container_name: evm2-1
    # logging:
    #   driver: none
    ports:
      - "8547:8545"

  relayer1:
    container_name: example_relayer1
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_1.json --fresh"
    depends_on:
      - evm1-1
      - evm2-1
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer2:
    container_name: example_relayer2
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_2.json --fresh"
    depends_on:
      - evm1-1
      - evm2-1
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer3:
    container_name: example_relayer3
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_3.json --fresh"
    depends_on:
      - evm1-1
      - evm2-1
    volumes:
      - ./cfg:/cfg
    restart: always

  fee-oracle:
    container_name: fee-oracle
    image: "ghcr.io/sygmaprotocol/sygma-fee-oracle:latest"
    command: go run main.go server -r ./fee-oracle-config/resource.json -c ./fee-oracle-config/config.yaml -d ./fee-oracle-config/domain.json
    depends_on:
      - evm1-1
      - evm2-1
    volumes:
      - ./fee-oracle-config:/app/feeOracle/fee-oracle-config
    ports:
      - "8091:8091"
    environment:
      - APP_MODE=debug
      - IDENTITY_KEY=71aec985a12cfcbabc7969845215ceac56038e87477c8337e373eab7b15796cf
      - IDENTITY_KEY_TYPE=secp256k1
